### PR TITLE
Update German Locale

### PR DESCRIPTION
**Pull request by Merathilis**

### CODE REVIEW

**Comment by Benik** [comment]
:dancers:

**Comment by Benik** [comment]
It's already in ElvUI. My bad

**Comment by Merathilis** [comment]
that's strange, it is not localized
wowscrnshot_031715_225600

**Comment by Benik** [comment]
... blaah in ElvUI it's L["Credits"] not L["Credits:"]. Reverted :)

**Comment by Merathilis** [comment]
lol ^^

**Comment by Benik** [comment]
Daaaamn just saw your comment under the pic LOL

**Comment by Merathilis** [comment]
hahahahaha :D

**Pull request merged**
